version: "3"

services:
  gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      POLYXIA_GATEWAY_MORTY_API_ENDPOINT: "http://localhost:8081/v1"
      POLYXIA_GATEWAY_NLU_API_ENDPOINT: "http://localhost:8082/v1"
      POLYXIA_GATEWAY_MORTY_ADDR: "0.0.0.0"
      POLYXIA_GATEWAY_MORTY_PORT: "8080"
