version: "3"

services:
  gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      MORTY_API_ENDPOINT: "http://localhost:8081/v1/functions/build"
      NLU_API_ENDPOINT: "http://localhost:8082/v1/skills"