openapi: 3.0.0
info:
  title: Gateway API
  version: 1.0.0
paths:
  /nlu:
    post:
      summary: Send a payload to recieve a response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AskPayload'
      responses:
        '200':
          description: NLU return the response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NLUResponse'
  /skills:
    post:
      summary: Create a new skill
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the skill.
                intents_json:
                  type: string
                  format: binary
                  description: The JSON file containing intents data.
                function_archive:
                  type: string
                  format: binary
                  description: The ZIP file containing function code.
      responses:
        '200':
          description: Skill created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APISucess'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
components:
  schemas:
    AskPayload:
      type: object
      properties:
        input_text:
          type: string
    NLUResponse:
      type: object
      properties:
        response:
          type: string
    APIError:
      type: object
      properties:
        StatusCode:
          type: integer
          format: int32
        Message:
          type: string
    APISucess:
      type: object
      properties:
        StatusCode:
          type: integer
          format: int32
        Message:
          type: string
