name: Release
on:
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      # - name: Test
      #   run: go test -v ./...

  release:
    strategy:
      matrix:
        goarch: ["amd64", "arm64"]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: ${{ matrix.goarch }}
          goversion: "1.20"
          binary_name: gateway
